# -*- coding: utf-8 -*-
"""Kairosys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCEZV7cGrUYm91bpWNcQnxz7UMze6AGe
"""

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Benchmark + 9 ETF sectoriels US (tous dispo depuis 1998, zéro trou)
benchmark = "SPY"
sectors = ["XLK", "XLF", "XLV", "XLY", "XLP", "XLI", "XLE", "XLU", "XLB"]
tickers = [benchmark] + sectors

raw = yf.download(tickers, start="2010-01-01", auto_adjust=False)["Adj Close"]
raw = raw.ffill(limit=5).dropna()

print(raw.shape)
print(raw.index.min().date(), "->", raw.index.max().date())
print(raw.isna().sum().sum(), "NaN")
raw.tail(3)

# --- Strategy 1: 200-day trend-following on SPY ---
spy = raw["SPY"].copy()

# 200-day moving average
ma200 = spy.rolling(window=200).mean()

# Signal: 1 if price > MA200 (invested), 0 otherwise (cash)
# .shift(1) = decision made yesterday, applied today => no look-ahead
signal = (spy > ma200).astype(int).shift(1)

# SPY daily returns
spy_ret = spy.pct_change()

# Strategy return = signal * same-day return
strat_ret_gross = signal * spy_ret

print("Time invested:", f"{signal.mean():.0%} of the period")
print("Number of position changes:", int(signal.diff().abs().sum()))
strat_ret_gross.tail(3)

# --- Costs + comparison vs SPY (buy & hold) ---
cost_per_change = 0.0010  # 10 bps per position change (entry or exit)

# Cost applied each time the position flips
costs = signal.diff().abs() * cost_per_change
strat_ret_net = strat_ret_gross - costs

# Equity curves (start at 1)
eq_strat = (1 + strat_ret_net).cumprod()
eq_spy   = (1 + spy_ret).cumprod()

# --- Performance metrics ---
def perf(returns):
    returns = returns.dropna()
    ann_ret = (1 + returns).prod() ** (252 / len(returns)) - 1
    ann_vol = returns.std() * np.sqrt(252)
    sharpe  = ann_ret / ann_vol if ann_vol > 0 else np.nan
    eq = (1 + returns).cumprod()
    max_dd = (eq / eq.cummax() - 1).min()
    return ann_ret, ann_vol, sharpe, max_dd

r1, v1, s1, d1 = perf(strat_ret_net)
rb, vb, sb, db = perf(spy_ret)

print("                 Strategy 1 (trend)   SPY (buy & hold)")
print(f"Annual return    {r1:>8.2%}            {rb:>8.2%}")
print(f"Annual vol       {v1:>8.2%}            {vb:>8.2%}")
print(f"Sharpe           {s1:>8.2f}            {sb:>8.2f}")
print(f"Max drawdown     {d1:>8.2%}            {db:>8.2%}")

# --- Equity curve: Strategy 1 vs SPY ---
plt.figure(figsize=(12, 6))
plt.plot(eq_strat, label="Strategy 1  Trend-following (200d)", linewidth=1.5)
plt.plot(eq_spy, label="SPY (buy & hold)", linewidth=1.5, alpha=0.8)
plt.title("Strategy 1 vs SPY  Growth of $1")
plt.ylabel("Cumulative value")
plt.legend()
plt.grid(alpha=0.3)
plt.yscale("log")  # log scale: % moves are comparable over 17 years
plt.savefig("strategy1_equity.png", dpi=120, bbox_inches="tight")
plt.show()

# --- Strategy 2: Sector momentum rotation ---
prices = raw[sectors].copy()   # 9 sector ETFs (SPY excluded)

# 12-1 momentum: last 12 months return, skipping the most recent month
# (standard momentum definition, avoids short-term reversal noise)
momentum = prices.shift(21) / prices.shift(252) - 1

# Rank sectors each day, keep the top 3 (equal weight)
TOP_N = 3
ranks = momentum.rank(axis=1, ascending=False)
weights = (ranks <= TOP_N).astype(float)
weights = weights.div(weights.sum(axis=1), axis=0)   # equal weight, sums to 1

# Rebalance monthly: hold weights steady within the month
weights_monthly = weights.resample("ME").first().reindex(prices.index).ffill()

print("First valid date:", momentum.dropna().index.min().date())
print("Avg number of positions:", f"{(weights_monthly > 0).sum(axis=1).mean():.1f}")
weights_monthly.tail(3)

# --- Strategy 2 backtest: returns, costs, vs SPY ---
sector_ret = prices.pct_change()

# Portfolio return = yesterday's weights * today's returns (no look-ahead)
strat2_ret_gross = (weights_monthly.shift(1) * sector_ret).sum(axis=1)

# Turnover = how much the book changes at each rebalance
turnover = (weights_monthly - weights_monthly.shift(1)).abs().sum(axis=1)
strat2_costs = turnover * cost_per_change
strat2_ret_net = strat2_ret_gross - strat2_costs

# Align SPY on the same period (momentum needs 1 year of history)
start = momentum.dropna().index.min()
strat2_ret_net = strat2_ret_net.loc[start:]
spy_ret_aligned = spy_ret.loc[start:]

# Metrics (reusing perf() from cell 3)
r2, v2, s2, d2 = perf(strat2_ret_net)
rb2, vb2, sb2, db2 = perf(spy_ret_aligned)

print("Avg monthly turnover:", f"{turnover[turnover > 0].mean():.2f}")
print()
print("                 Strategy 2 (rotation)   SPY (buy & hold)")
print(f"Annual return    {r2:>8.2%}              {rb2:>8.2%}")
print(f"Annual vol       {v2:>8.2%}              {vb2:>8.2%}")
print(f"Sharpe           {s2:>8.2f}              {sb2:>8.2f}")
print(f"Max drawdown     {d2:>8.2%}              {db2:>8.2%}")

# --- Strategy 2 (attempt 1): dual momentum (relative + absolute filter) ---
# Keep top-3 sectors, but only those with positive absolute momentum.
# Non-qualifying slots go to cash (0% return, conservative).

in_top = momentum.rank(axis=1, ascending=False) <= TOP_N
positive = momentum > 0
hold = (in_top & positive).astype(float)

weights_dm = hold.div(TOP_N)   # fixed 1/3 per slot => cash when <3 qualify
weights_dm_monthly = weights_dm.resample("ME").first().reindex(prices.index).ffill()

# Backtest
strat2b_gross = (weights_dm_monthly.shift(1) * sector_ret).sum(axis=1)
turnover_dm = (weights_dm_monthly - weights_dm_monthly.shift(1)).abs().sum(axis=1)
strat2b_net = (strat2b_gross - turnover_dm * cost_per_change).loc[start:]

r2b, v2b, s2b, d2b = perf(strat2b_net)

print("            Rotation (plain)   Rotation + abs filter   SPY")
print(f"Ann return  {r2:>7.2%}           {r2b:>7.2%}              {rb2:>7.2%}")
print(f"Ann vol     {v2:>7.2%}           {v2b:>7.2%}              {vb2:>7.2%}")
print(f"Sharpe      {s2:>7.2f}           {s2b:>7.2f}              {sb2:>7.2f}")
print(f"Max DD      {d2:>7.2%}           {d2b:>7.2%}              {db2:>7.2%}")
print(f"% in cash   {(weights_dm_monthly.sum(axis=1) < 0.99).mean():>7.0%}")

# --- Strategy 2 (attempt 2): sector rotation with a market trend overlay ---
# Hold top-3 sectors by momentum, but only when SPY is above its 200d MA.
# When SPY is below its MA200 (market downtrend), go fully to cash.

market_on = (spy > ma200).shift(1)   # daily trend filter, no look-ahead
market_on = market_on.reindex(prices.index).fillna(False)

# Base weights = plain top-3 rotation (equal weight)
weights_final = weights_monthly.copy()
# Kill all positions on days the market filter is off (=> cash)
weights_final = weights_final.mul(market_on.astype(float), axis=0)

# Backtest
strat2c_gross = (weights_final.shift(1) * sector_ret).sum(axis=1)
turnover_c = (weights_final - weights_final.shift(1)).abs().sum(axis=1)
strat2c_net = (strat2c_gross - turnover_c * cost_per_change).loc[start:]

r2c, v2c, s2c, d2c = perf(strat2c_net)

print("            Rotation plain   Rotation + trend overlay   SPY")
print(f"Ann return  {r2:>7.2%}          {r2c:>7.2%}                 {rb2:>7.2%}")
print(f"Ann vol     {v2:>7.2%}          {v2c:>7.2%}                 {vb2:>7.2%}")
print(f"Sharpe      {s2:>7.2f}          {s2c:>7.2f}                 {sb2:>7.2f}")
print(f"Max DD      {d2:>7.2%}          {d2c:>7.2%}                 {db2:>7.2%}")
print(f"% in cash   {(weights_final.sum(axis=1) < 0.99).mean():>7.0%}")

# --- Combination: are the two strategies complementary? ---
# Align both net return streams on their common period
s1 = strat_ret_net.loc[start:]      # Strategy 1 (trend-following)
s2 = strat2_ret_net                 # Strategy 2 (plain rotation)

combo = 0.5 * s1 + 0.5 * s2         # naive 50/50 portfolio

print("Correlation between the two strategies:", f"{s1.corr(s2):.2f}")
print()
rc, vc, sc, dc = perf(combo)
print("            Strat 1   Strat 2   Combo 50/50   SPY")
print(f"Ann return  {perf(s1)[0]:>6.2%}   {perf(s2)[0]:>6.2%}    {rc:>6.2%}      {rb2:>6.2%}")
print(f"Ann vol     {perf(s1)[1]:>6.2%}   {perf(s2)[1]:>6.2%}    {vc:>6.2%}      {vb2:>6.2%}")
print(f"Sharpe      {perf(s1)[2]:>6.2f}   {perf(s2)[2]:>6.2f}    {sc:>6.2f}      {sb2:>6.2f}")
print(f"Max DD      {perf(s1)[3]:>6.2%}   {perf(s2)[3]:>6.2%}    {dc:>6.2%}      {db2:>6.2%}")

# --- Final chart: both strategies, the combo, and SPY ---
eq_s1    = (1 + s1).cumprod()
eq_s2    = (1 + s2).cumprod()
eq_combo = (1 + combo).cumprod()
eq_bench = (1 + spy_ret_aligned).cumprod()

plt.figure(figsize=(12, 6))
plt.plot(eq_s1,    label="Strategy 1  Trend-following", linewidth=1.3)
plt.plot(eq_s2,    label="Strategy 2  Sector rotation", linewidth=1.3)
plt.plot(eq_combo, label="Combo 50/50", linewidth=2.0, color="black")
plt.plot(eq_bench, label="SPY (buy & hold)", linewidth=1.3, alpha=0.7, linestyle="--")
plt.title("Two strategies vs their combination vs SPY  Growth of $1")
plt.ylabel("Cumulative value")
plt.legend()
plt.grid(alpha=0.3)
plt.yscale("log")
plt.savefig("equity_curves.png", dpi=120, bbox_inches="tight")
plt.show()

# --- Correlation matrix + extended stats ---

# 1. Correlation between the three return streams and SPY
corr_df = pd.DataFrame({
    "Strat 1 (trend)":    s1,
    "Strat 2 (rotation)": s2,
    "Combo 50/50":        combo,
    "SPY":                spy_ret_aligned,
}).dropna()

print("Correlation matrix (daily returns):")
print(corr_df.corr().round(2))
print()

# 2. Extended performance stats
def perf_full(returns, weights_series=None):
    r = returns.dropna()
    ann_ret = (1 + r).prod() ** (252 / len(r)) - 1
    ann_vol = r.std() * np.sqrt(252)
    sharpe  = ann_ret / ann_vol if ann_vol > 0 else np.nan
    downside = r[r < 0].std() * np.sqrt(252)
    sortino = ann_ret / downside if downside > 0 else np.nan
    eq = (1 + r).cumprod()
    max_dd = (eq / eq.cummax() - 1).min()
    calmar = ann_ret / abs(max_dd) if max_dd < 0 else np.nan
    return ann_ret, ann_vol, sharpe, sortino, max_dd, calmar

print(f"{'':20}{'Return':>9}{'Vol':>9}{'Sharpe':>9}{'Sortino':>9}{'MaxDD':>9}{'Calmar':>9}")
for name, r in [("Strat 1 (trend)", s1), ("Strat 2 (rotation)", s2),
                ("Combo 50/50", combo), ("SPY", spy_ret_aligned)]:
    ar, av, sh, so, dd, ca = perf_full(r)
    print(f"{name:20}{ar:>8.2%}{av:>8.2%}{sh:>9.2f}{so:>9.2f}{dd:>8.2%}{ca:>9.2f}")